[versions]
appcompat = "1.7.0"
activity = "1.10.0"
#parcelize = "2.0.0"

compose = "1.7.6"
composeMaterial3 = "1.3.1"
composeConstraintLayout = "1.1.0"
composeNavigation = "2.7.7"
hiltNavigationCompose = "1.2.0"
hilt = "2.54"

jdkDesugaring="2.1.4"

[libraries]
jdk-desugaring = { module = "com.android.tools:desugar_jdk_libs", version.ref = "jdkDesugaring" }

activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }

appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat"}
appcompat-resources = { group = "androidx.appcompat", name = "appcompat-resources", version.ref = "appcompat"}

compose-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "composeConstraintLayout" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "compose" }
compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout", version.ref = "compose" }
compose-material-iconsExtended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "compose" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "composeMaterial3" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "compose" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
compose-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
#compose-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }

hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }

#navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "composeNavigation" }
[plugins]

[bundles]
appcompat = [
    "appcompat",
    "appcompat-resources",
]
compose = [
    "compose-foundation",
    "compose-foundation-layout",
    "compose-material-iconsExtended",
    "compose-material3",
    "compose-runtime",
    "compose-ui",
    "compose-tooling",
]
hilt = [
    "hilt-android",
#    "hilt-navigation-compose",
]
